name: Project CI

on: push

jobs:
  job_1:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest data-collection/test_main.py  
      